[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false
default = ["anchor-debug"]
anchor-debug = []

[programs.localnet]
amms = "95RfKC6UDmxeMjR9AAhF9xVauYmeFQawVK5W51tHn8wb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
